### ISSUE TITLE
Accept-Datetime-Format bug

### ISSUE THREAD

**Issue by alekna** [oanda/v20-python#16]
`Accept-Datetime-Format` is not respected in heartbeat messages:

This is what I get when `Accept-Datetime-Format` is set to `UNIX`

```
Pricing Heartbeat 2016-12-13T13:41:27.222512838Z
================================================

type = HEARTBEAT
time = 2016-12-13T13:41:27.222512838Z

Type = PRICE
instrument = EUR_NZD
time = 1481636487.426472413
status = tradeable
bids = [1]
asks = [1]
closeoutBid = 1.47247
closeoutAsk = 1.47301

Type = PRICE
instrument = EUR_HKD
time = 1481636487.296723637
status = tradeable
bids = [1]
asks = [1]
closeoutBid = 8.24445
closeoutAsk = 8.24594
```

Could you please also unify `__str__()` implementation for different entities? Currently it's not the same at least for `PRICE` and `HEARTBEAT` messages. I suppose `Type` in `PRICE` should be lowercase.

**Comment by dmpettyp** [comment]
The heartbeat problem was a known bug that was fixed recently. I'll check why it hasn't been released yet. To my knowledge it should *at least* be on fxtrade practice by now.

The __str__ inconsistencies are because those strings are generated using the property's "display names", however no display names were provided for those entities. I'll add them and push out a build. The truth is I'm not super happy with the the __str__ representations provided, but they are what we have for now. Maybe just dumping YAML from __str__ would look nice...

**Comment by alekna** [comment]
Let me know when it is released to fxTrade live.

As for dumping YAML, I think it's a good idea. As long as it makes output consistent.

**Comment by dmpettyp** [comment]
The fix should be on fxtrade practice, but won't be promoted until the first maintenance of the new year (likely Jan 6)

**Comment by alekna** [comment]
Any updates on this issue?

**Comment by alekna** [comment]
Thanks for fixing this.

**Comment by dmpettyp** [comment]
Ah, thanks for checking and verifying.
